# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "songtang209"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 5000

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
# keywords to search
keywords:
    "RES": 
        filters: ["Referring Expression Segmentation", "Referring Image Segmentation", "Language-based Image Segmentation"]
    "RVOS": 
        filters: ["Referring Video Object Segmentation", "Referring Video-Object Segmentation", "Text-based Video Segmentation"]
    "RMOT": 
        filters: ["Referring Multi-Object Tracking"]
    "RVOT": 
        filters: ["Referring Video Object Tracking", "Referring Single Object Tracking", "Vision-Language Tracking"]
    "AVS": 
        filters: ["Audio-Visual Segmentation", "Audio Visual Segmentation"]
    "3D-RES":
          filters: ["3D Referring Expression Segmentation"]  

  


